from fastapi import FastAPI
from contextlib import asynccontextmanager
from fastapi.middleware.cors import CORSMiddleware
from app.core.config import settings


from app.api.user_chat.chat_rag_v2 import chat_rag_v2_router

from app.api.appwrite.folder_create import folder_create_router
from app.api.appwrite.document_folder_create import document_folder_router

from app.api.admin_upload_data.pdf_text_v3 import pdf_text_router_v3
from app.api.admin_upload_data.qna import qna_router
from app.api.admin_upload_data.raw import raw_router


from app.api.delete.delete_from_pinecone import delete_from_pine_cone_router


@asynccontextmanager
async def lifespan(app: FastAPI):
    
    if not all([
        settings.OPENAI_API_KEY,
        settings.PINECONE_API_KEY,
        settings.PINECONE_ENV,
        settings.PINECONE_INDEX_NAME
    ]):
        raise ValueError("Missing required environment variables")
    yield
    

app = FastAPI(
    title=settings.PROJECT_NAME,
    version=settings.VERSION,
    description=settings.DESCRIPTION,
    openapi_url=f"{settings.API_V1_STR}/openapi.json",
    lifespan=lifespan
)

# Set up CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)




#USER CHAT ROUTE
app.include_router(chat_rag_v2_router)
# app.include_router(user_chat_router)

#FOLDER MANAGMENT ROUTES
app.include_router(folder_create_router)
app.include_router(document_folder_router)

#UPLOAD DATA ROUTES [PDF / JSON / RAW]
app.include_router(pdf_text_router_v3)
app.include_router(qna_router)
app.include_router(raw_router) 


#DELETE FROM PINE CONE AND UPDATE IN APPWRITE
app.include_router(delete_from_pine_cone_router)







@app.get("/health")
async def health():
    return {"status": "healthy"}

@app.get("/")
async def read_root():
    return {
        "message": "THIS IS THE BASE URL FOR THE CHAT BOT",
        "endpoints": {
            "/health": {
                "method": "GET",
                "description": "Check if the server is healthy.",
                "response": {"status": "healthy"}
            },
            "/testing": {
                "method": "POST",
                "description": "Test endpoint that requires a POST request with a message in the body. The server will respond directly from OpenAI's model.",
                "request_body": {
                    "message": "string (Your message to OpenAI model)"
                },
                "response": {
                    "response": "string (Direct response from OpenAI model)"
                }
            },
            "/chat": {
                "method": "POST",
                "description": "Chat endpoint using Pinecone and RAG (Retrieval-Augmented Generation). Requires a POST request with a query message in the body.",
                "request_body": {
                    "query": "string (Your query for chat)"
                },
                "response": {
                    "response": "string (Response generated by GPT model based on Pinecone retrieval)"
                }
            }
        },
        "note": "If you encounter a CORS error, it is due to your endpoint not being allowed. Please contact the server team so that they can add your endpoint to the allowed list."
    }
